import { DOMCacheGetOrSet } from './Cache/DOM'

export type iconSize = 32 | 48 | 56 | 64

export interface SpriteSheet {
  name: string
  elementNames: (string | null)[]
  iconSize: iconSize // All icons in the sheet must be the same size.
  rows: number
  columns: number
  aliases?: Array<{
    elementName: string
    iconIndex: number
    displaySize: number
  }>
}

// When you make new icons (or are converting old ones) make sure to add to this list
export const spriteSheets: SpriteSheet[] = [
  {
    name: 'BuildingsAndUpgrades',
    elementNames: [
      'coin1',
      'coin2',
      'coin3',
      'coin4',
      'coin5',
      'accelerator',
      'multiplier',
      'acceleratorboost',
      null,
      null,
      'diamond1',
      'diamond2',
      'diamond3',
      'diamond4',
      'diamond5',
      'buycrystalupgrade1',
      'buycrystalupgrade2',
      'buycrystalupgrade3',
      'buycrystalupgrade4',
      'buycrystalupgrade5',
      'mythos1',
      'mythos2',
      'mythos3',
      'mythos4',
      'mythos5',
      'buyConstantUpgrade1',
      'buyConstantUpgrade2',
      'buyConstantUpgrade3',
      'buyConstantUpgrade4',
      'buyConstantUpgrade5',
      'particles1',
      'particles2',
      'particles3',
      'particles4',
      'particles5',
      'buyConstantUpgrade6',
      'buyConstantUpgrade7',
      'buyConstantUpgrade8',
      'buyConstantUpgrade9',
      'buyConstantUpgrade10',
      'tesseracts1',
      'tesseracts2',
      'tesseracts3',
      'tesseracts4',
      'tesseracts5',
      null,
      null,
      null,
      null,
      null
    ],
    iconSize: 32,
    rows: 5,
    columns: 10
  },
  {
    name: 'AntsAndMasteries',
    elementNames: [
      'antTier1Image',
      'antTier2Image',
      'antTier3Image',
      'antTier4Image',
      'antTier5Image',
      'antTier6Image',
      'antTier7Image',
      'antTier8Image',
      'antTier9Image',
      'antMastery1Image',
      'antMastery2Image',
      'antMastery3Image',
      'antMastery4Image',
      'antMastery5Image',
      'antMastery6Image',
      'antMastery7Image',
      'antMastery8Image',
      'antMastery9Image'
    ],
    iconSize: 32,
    rows: 2,
    columns: 9
  },
  {
    name: 'AntUpgrades',
    elementNames: [
      'antUpgrade1Image',
      'antUpgrade2Image',
      'antUpgrade3Image',
      'antUpgrade4Image',
      'antUpgrade5Image',
      'antUpgrade6Image',
      'antUpgrade10Image',
      'antUpgrade12Image',
      'antUpgrade13Image',
      'antUpgrade7Image',
      'antUpgrade8Image',
      'antUpgrade9Image',
      'antUpgrade11Image',
      'antUpgrade14Image',
      'antUpgrade15Image',
      'antUpgrade16Image'
    ],
    iconSize: 56,
    rows: 2,
    columns: 8
  },
  {
    name: 'Divinity',
    elementNames: [
      'speedRuneBlessing',
      'duplicationRuneBlessing',
      'prismRuneBlessing',
      'thriftRuneBlessing',
      'superiorIntellectRuneBlessing',
      'speedRuneSpirit',
      'duplicationRuneSpirit',
      'prismRuneSpirit',
      'thriftRuneSpirit',
      'superiorIntellectRuneSpirit'
    ],
    iconSize: 64,
    rows: 2,
    columns: 5
  },
  {
    name: 'Challenges',
    elementNames: [
      'challenge1',
      'challenge2',
      'challenge3',
      'challenge4',
      'challenge5',
      'challenge6',
      'challenge7',
      'challenge8',
      'challenge9',
      'challenge10',
      'challenge11',
      'challenge12',
      'challenge13',
      'challenge14',
      'challenge15',
      'noSingularityUpgrades',
      'oneChallengeCap',
      'limitedAscensions',
      'noQuarkUpgrades',
      'noOcteracts',
      'noAmbrosiaUpgrades',
      'limitedTime',
      'sadisticPrequel',
      'taxmanLastStand',
      'barDependence'
    ],
    iconSize: 64,
    rows: 5,
    columns: 5
  },
  {
    name: 'WowPasses',
    elementNames: [
      'seasonPass',
      'seasonPass2',
      'seasonPass3',
      'seasonPassY',
      'seasonPassZ',
      'seasonPassLost',
      'seasonPassInfinity'
    ],
    iconSize: 64,
    rows: 1,
    columns: 7,
    aliases: [{ elementName: 'shopFamilyRowIcon-seasonPass', iconIndex: 0, displaySize: 24 }]
  },
  {
    name: 'DiceOfAsmodeus',
    elementNames: [
      'shopRedLuck1',
      'shopRedLuck2',
      'shopRedLuck3',
      'shopRedLuck4'
    ],
    iconSize: 64,
    rows: 1,
    columns: 4,
    aliases: [{ elementName: 'shopFamilyRowIcon-shopRedLuck1', iconIndex: 0, displaySize: 24 }]
  },
  {
    name: 'PLATCalculators',
    elementNames: [
      'calculator',
      'calculator2',
      'calculator3',
      'calculator4',
      'calculator5',
      'calculator6',
      'calculator7'
    ],
    iconSize: 64,
    rows: 1,
    columns: 7,
    aliases: [{ elementName: 'shopFamilyRowIcon-calculator', iconIndex: 0, displaySize: 24 }]
  },
  {
    name: 'PlatonicUpgrades',
    elementNames: [
      'platUpg1Image',
      'platUpg2Image',
      'platUpg3Image',
      'platUpg4Image',
      'platUpg5Image',
      'platUpg6Image',
      'platUpg7Image',
      'platUpg8Image',
      'platUpg9Image',
      'platUpg10Image',
      'platUpg11Image',
      'platUpg12Image',
      'platUpg13Image',
      'platUpg14Image',
      'platUpg15Image',
      'platUpg16Image',
      'platUpg17Image',
      'platUpg18Image',
      'platUpg19Image',
      'platUpg20Image'
    ],
    iconSize: 32,
    rows: 4,
    columns: 5
  },
  {
    name: 'Hepteracts',
    elementNames: [
      'chronosHepteractImage',
      'hyperrealismHepteractImage',
      'quarkHepteractImage',
      'challengeHepteractImage',
      'abyssHepteractImage',
      'acceleratorHepteractImage',
      'acceleratorBoostHepteractImage',
      'multiplierHepteractImage',
      'hepteractToQuarkImage',
      'overfluxPowderImage'
    ],
    iconSize: 56,
    rows: 3,
    columns: 4,
    aliases: [
      { elementName: 'eventBuffPowderConversionIcon', iconIndex: 9, displaySize: 32 },
      { elementName: 'consumableBuffPowderConversionIcon', iconIndex: 9, displaySize: 32 }
    ]
  },
  {
    name: 'Octeracts',
    elementNames: [
      null,
      null,
      'octeractStarterImage',
      'octeractGainImage',
      'octeractGain2Image',
      'octeractAscensionsOcteractGainImage',
      'octeractOneMindImproverImage',
      'octeractFastForwardImage',
      'octeractSingUpgradeCapImage',
      'octeractGQCostReduceImage',
      'octeractQuarkGainImage',
      'octeractQuarkGain2Image',
      'octeractImprovedQuarkHeptImage',
      'octeractExportQuarksImage',
      'octeractImprovedDaily3Image',
      'octeractImprovedDaily2Image',
      'octeractImprovedDailyImage',
      'octeractImprovedFreeImage',
      'octeractImprovedFree2Image',
      'octeractImprovedFree3Image',
      'octeractImprovedFree4Image',
      null,
      'octeractAscensions2Image',
      'octeractAscensionsImage',
      'octeractImprovedGlobalSpeedImage',
      'octeractImprovedAscensionSpeedImage',
      'octeractImprovedAscensionSpeed2Image',
      null,
      null,
      null,
      'octeractCorruptionImage',
      'octeractBonusTokens1Image',
      'octeractBonusTokens2Image',
      'octeractBonusTokens3Image',
      'octeractBonusTokens4Image',
      null,
      'octeractObtainium1Image',
      'octeractOfferings1Image',
      'octeractAutoPotionSpeedImage',
      'octeractAutoPotionEfficiencyImage',
      null,
      null,
      null,
      null,
      'octeractInfiniteShopUpgradesImage',
      'octeractTalismanLevelCap1Image',
      'octeractTalismanLevelCap2Image',
      'octeractTalismanLevelCap3Image',
      'octeractTalismanLevelCap4Image',
      null,
      null,
      'octeractBlueberriesImage',
      'octeractAmbrosiaLuck2Image',
      'octeractAmbrosiaLuck3Image',
      'octeractAmbrosiaLuckImage',
      'octeractAmbrosiaLuck4Image',
      null,
      null,
      null,
      'octeractAmbrosiaGeneration2Image',
      'octeractAmbrosiaGeneration3Image',
      'octeractAmbrosiaGenerationImage',
      'octeractAmbrosiaGeneration4Image'
    ],
    iconSize: 32,
    rows: 9,
    columns: 7
  },
  {
    name: 'QuarkEnrichedCubes',
    elementNames: [
      'cubeToQuark',
      'tesseractToQuark',
      'hypercubeToQuark',
      'cubeToQuarkAll'
    ],
    iconSize: 64,
    rows: 1,
    columns: 4,
    aliases: [{ elementName: 'shopFamilyRowIcon-cubeToQuark', iconIndex: 0, displaySize: 24 }]
  },
  {
    name: 'CampaignTokens',
    elementNames: [
      'campaignTokenRewardIcon-sum',
      'campaignTokenRewardIcon-tutorial',
      'campaignTokenRewardIcon-cube',
      'campaignTokenRewardIcon-obtainium',
      'campaignTokenRewardIcon-offering',
      'campaignTokenRewardIcon-ascensionScore',
      null,
      'campaignTokenRewardIcon-quark',
      'campaignTokenRewardIcon-tax',
      'campaignTokenRewardIcon-c15',
      'campaignTokenRewardIcon-rune6',
      'campaignTokenRewardIcon-goldenQuark',
      'campaignTokenRewardIcon-octeract',
      'campaignTokenRewardIcon-ambrosiaLuck',
      'campaignTokenRewardIcon-blueberrySpeed'
    ],
    iconSize: 48,
    rows: 1,
    columns: 15
  },
  {
    name: 'Cubes',
    elementNames: [
      'cube1Image',
      'cube2Image',
      'cube3Image',
      'cube4Image',
      'cube5Image',
      'cube6Image',
      'cube7Image',
      'cube8Image',
      'cube9Image',
      'cube10Image',
      'tesseract1Image',
      'tesseract2Image',
      'tesseract3Image',
      'tesseract4Image',
      'tesseract5Image',
      'tesseract6Image',
      'tesseract7Image',
      'tesseract8Image',
      'tesseract9Image',
      'tesseract10Image',
      'hypercube1Image',
      'hypercube2Image',
      'hypercube3Image',
      'hypercube4Image',
      'hypercube5Image',
      'hypercube6Image',
      'hypercube7Image',
      'hypercube8Image',
      'hypercube9Image',
      'hypercube10Image',
      'platonicCube1Image',
      'platonicCube2Image',
      'platonicCube3Image',
      'platonicCube4Image',
      'platonicCube5Image',
      'platonicCube6Image',
      'platonicCube7Image',
      'platonicCube8Image',
      null,
      null
    ],
    iconSize: 32,
    rows: 4,
    columns: 10
  },
  {
    name: 'Researches',
    elementNames: [
      'research1Image',
      'research2Image',
      'research3Image',
      'research4Image',
      'research5Image',
      'research6Image',
      'research7Image',
      'research8Image',
      'research9Image',
      'research10Image',
      'research11Image',
      'research12Image',
      'research13Image',
      'research14Image',
      'research15Image',
      'research16Image',
      'research17Image',
      'research18Image',
      'research19Image',
      'research20Image',
      'research21Image',
      'research22Image',
      'research23Image',
      'research24Image',
      'research25Image',
      'research26Image',
      'research27Image',
      'research28Image',
      'research29Image',
      'research30Image',
      'research31Image',
      'research32Image',
      'research33Image',
      'research34Image',
      'research35Image',
      'research36Image',
      'research37Image',
      'research38Image',
      'research39Image',
      'research40Image',
      'research41Image',
      'research42Image',
      'research43Image',
      'research44Image',
      'research45Image',
      'research46Image',
      'research47Image',
      'research48Image',
      'research49Image',
      'research50Image',
      'research51Image',
      'research52Image',
      'research53Image',
      'research54Image',
      'research55Image',
      'research56Image',
      'research57Image',
      'research58Image',
      'research59Image',
      'research60Image',
      'research61Image',
      'research62Image',
      'research63Image',
      'research64Image',
      'research65Image',
      'research66Image',
      'research67Image',
      'research68Image',
      'research69Image',
      'research70Image',
      'research71Image',
      'research72Image',
      'research73Image',
      'research74Image',
      'research75Image',
      'research76Image',
      'research77Image',
      'research78Image',
      'research79Image',
      'research80Image',
      'research81Image',
      'research82Image',
      'research83Image',
      'research84Image',
      'research85Image',
      'research86Image',
      'research87Image',
      'research88Image',
      'research89Image',
      'research90Image',
      'research91Image',
      'research92Image',
      'research93Image',
      'research94Image',
      'research95Image',
      'research96Image',
      'research97Image',
      'research98Image',
      'research99Image',
      'research100Image',
      'research101Image',
      'research102Image',
      'research103Image',
      'research104Image',
      'research105Image',
      'research106Image',
      'research107Image',
      'research108Image',
      'research109Image',
      'research110Image',
      'research111Image',
      'research112Image',
      'research113Image',
      'research114Image',
      'research115Image',
      'research116Image',
      'research117Image',
      'research118Image',
      'research119Image',
      'research120Image',
      'research121Image',
      'research122Image',
      'research123Image',
      'research124Image',
      'research125Image',
      'research126Image',
      'research127Image',
      'research128Image',
      'research129Image',
      'research130Image',
      'research131Image',
      'research132Image',
      'research133Image',
      'research134Image',
      'research135Image',
      'research136Image',
      'research137Image',
      'research138Image',
      'research139Image',
      'research140Image',
      'research141Image',
      'research142Image',
      'research143Image',
      'research144Image',
      'research145Image',
      'research146Image',
      'research147Image',
      'research148Image',
      'research149Image',
      'research150Image',
      'research151Image',
      'research152Image',
      'research153Image',
      'research154Image',
      'research155Image',
      'research156Image',
      'research157Image',
      'research158Image',
      'research159Image',
      'research160Image',
      'research161Image',
      'research162Image',
      'research163Image',
      'research164Image',
      'research165Image',
      'research166Image',
      'research167Image',
      'research168Image',
      'research169Image',
      'research170Image',
      'research171Image',
      'research172Image',
      'research173Image',
      'research174Image',
      'research175Image',
      'research176Image',
      'research177Image',
      'research178Image',
      'research179Image',
      'research180Image',
      'research181Image',
      'research182Image',
      'research183Image',
      'research184Image',
      'research185Image',
      'research186Image',
      'research187Image',
      'research188Image',
      'research189Image',
      'research190Image',
      'research191Image',
      'research192Image',
      'research193Image',
      'research194Image',
      'research195Image',
      'research196Image',
      'research197Image',
      'research198Image',
      'research199Image',
      'research200Image'
    ],
    iconSize: 32,
    rows: 8,
    columns: 25
  },
  {
    name: 'Upgrades',
    elementNames: [
      'upg1Image',
      'upg2Image',
      'upg3Image',
      'upg4Image',
      'upg5Image',
      'upg21Image',
      'upg22Image',
      'upg23Image',
      'upg24Image',
      'upg25Image',
      'upg41Image',
      'upg42Image',
      'upg43Image',
      'upg44Image',
      'upg45Image',
      'upg61Image',
      'upg62Image',
      'upg63Image',
      'upg64Image',
      'upg65Image',
      'upg81Image',
      'upg82Image',
      'upg83Image',
      'upg84Image',
      'upg85Image',
      'upg101Image',
      'upg102Image',
      'upg103Image',
      'upg104Image',
      'upg105Image',
      'upg6Image',
      'upg7Image',
      'upg8Image',
      'upg9Image',
      'upg10Image',
      'upg26Image',
      'upg27Image',
      'upg28Image',
      'upg29Image',
      'upg30Image',
      'upg46Image',
      'upg47Image',
      'upg48Image',
      'upg49Image',
      'upg50Image',
      'upg66Image',
      'upg67Image',
      'upg68Image',
      'upg69Image',
      'upg70Image',
      'upg86Image',
      'upg87Image',
      'upg88Image',
      'upg89Image',
      'upg90Image',
      'upg106Image',
      'upg107Image',
      'upg108Image',
      'upg109Image',
      'upg110Image',
      'upg11Image',
      'upg12Image',
      'upg13Image',
      'upg14Image',
      'upg15Image',
      'upg31Image',
      'upg32Image',
      'upg33Image',
      'upg34Image',
      'upg35Image',
      'upg51Image',
      'upg52Image',
      'upg53Image',
      'upg54Image',
      'upg55Image',
      'upg71Image',
      'upg72Image',
      'upg73Image',
      'upg74Image',
      'upg75Image',
      'upg91Image',
      'upg92Image',
      'upg93Image',
      'upg94Image',
      'upg95Image',
      'upg111Image',
      'upg112Image',
      'upg113Image',
      'upg114Image',
      'upg115Image',
      'upg16Image',
      'upg17Image',
      'upg18Image',
      'upg19Image',
      'upg20Image',
      'upg36Image',
      'upg37Image',
      'upg38Image',
      'upg39Image',
      'upg40Image',
      'upg56Image',
      'upg57Image',
      'upg58Image',
      'upg59Image',
      'upg60Image',
      'upg76Image',
      'upg77Image',
      'upg78Image',
      'upg79Image',
      'upg80Image',
      'upg96Image',
      'upg97Image',
      'upg98Image',
      'upg99Image',
      'upg100Image',
      'upg116Image',
      'upg117Image',
      'upg118Image',
      'upg119Image',
      'upg120Image',
      'upg121Image',
      'upg122Image',
      'upg123Image',
      'upg124Image',
      'upg125Image',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null
    ],
    iconSize: 32,
    rows: 5,
    columns: 30
  }
]

export const spritePlaceholder = 'Pictures/img_transparent.png'

export const registerSpriteAlias = (sourceElementName: string, elementName: string, displaySize: number) => {
  for (const sheet of spriteSheets) {
    const iconIndex = sheet.elementNames.indexOf(sourceElementName)
    if (iconIndex !== -1) {
      sheet.aliases ??= []
      sheet.aliases.push({ elementName, iconIndex, displaySize })
      return
    }
  }
}

// A null value marks a lookup as started; a string stores the fallback found for that source.
const spriteSheetFallbacks = new Map<string, string | null>()
const activeSpriteSheetSources = new Map<string, string>()

const updateIconFromSprite = (
  sheet: SpriteSheet,
  src: string,
  elementName: string,
  iconIndex: number,
  displaySize: number = sheet.iconSize
) => {
  const element = DOMCacheGetOrSet(elementName)
  element.style.backgroundImage = `url('${src}')`
  element.style.backgroundPosition = `${-(iconIndex % sheet.columns) * displaySize}px ${
    -Math.floor(iconIndex / sheet.columns) * displaySize
  }px`
  element.style.backgroundSize = `${sheet.columns * displaySize}px ${sheet.rows * displaySize}px`
  element.style.backgroundRepeat = 'no-repeat'
  element.style.width = `${displaySize}px`
  element.style.height = `${displaySize}px`
}

const updateIconsFromSpriteSheet = (sheet: SpriteSheet, folderUsed: string) => {
  const requestedSrc = `Pictures/${folderUsed}/Sprite Sheets/${sheet.name}.png`
  const resolvedSrc = spriteSheetFallbacks.get(requestedSrc) ?? requestedSrc
  activeSpriteSheetSources.set(sheet.name, resolvedSrc)

  for (const [iconIndex, elementName] of sheet.elementNames.entries()) {
    if (elementName === null) {
      continue
    }

    updateIconFromSprite(sheet, resolvedSrc, elementName, iconIndex)
  }

  for (const alias of sheet.aliases ?? []) {
    updateIconFromSprite(sheet, resolvedSrc, alias.elementName, alias.iconIndex, alias.displaySize)
  }

  if (folderUsed === 'Default' || resolvedSrc !== requestedSrc || spriteSheetFallbacks.has(requestedSrc)) {
    return
  }

  spriteSheetFallbacks.set(requestedSrc, null)
  const probe = new Image()
  probe.addEventListener('error', () => {
    const fallbackSrc = `Pictures/Default/Sprite Sheets/${sheet.name}.png`
    spriteSheetFallbacks.set(requestedSrc, fallbackSrc)

    if (activeSpriteSheetSources.get(sheet.name) === resolvedSrc) {
      updateIconsFromSpriteSheet(sheet, folderUsed)
    }
  }, { once: true })
  probe.src = requestedSrc
}

export const updateIconsFromSprites = (folderUsed: string) => {
  for (const sheet of spriteSheets) {
    updateIconsFromSpriteSheet(sheet, folderUsed)
  }
}
