name: ci

on:
  push:
    paths-ignore:
      - '*.md'
      - '*.json'
  pull_request:
    paths-ignore:
      - '*.md'
      - '*.json'

env:
  CI: true

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [18.x]
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Install
        run: |
          npm install
      - name: Check
        run: |
          npm run check:tsc
      - name: Run linter
        run: |
          npm run lint
          npm run csslint
