name: ci

on:
  push:
    branches: master
    paths-ignore:
      - '*.md'
      - '*.json'
  pull_request:
    paths-ignore:
      - '*.md'
      - '*.json'

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Use Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: lts/*
      - name: Install
        run: |
          npm ci
      - name: Check
        run: |
          npm run check:tsc
      - name: Run linter
        run: |
          npm run lint
          npm run csslint
